import Foundation

// MARK: - Extended Localization Keys

/// New localization keys added in v2.0 feature modules.
/// Integrates with the existing String(localized:) system backed by Localizable.xcstrings.
extension L10n {

    // MARK: - Store (内购)
    public static let storeTitle = String(localized: "store.title")
    public static let storeSubtitle = String(localized: "store.subtitle")
    public static let storeNoAds = String(localized: "store.noAds")
    public static let storeNoTracking = String(localized: "store.noTracking")
    public static let storePrivacyFirst = String(localized: "store.privacyFirst")
    public static let storePurchased = String(localized: "store.purchased")
    public static let storeDone = String(localized: "store.done")
    public static let storeTierFree = String(localized: "store.tier.free")
    public static let storeTierCore = String(localized: "store.tier.core")
    public static let storeTierPro = String(localized: "store.tier.pro")
    public static let storeTierAI = String(localized: "store.tier.ai")
    public static let storeTierCloud = String(localized: "store.tier.cloud")
    public static let storeCoreUnlock = String(localized: "store.product.coreUnlock")
    public static let storeLifetimePro = String(localized: "store.product.lifetimePro")
    public static let storeAIMonthly = String(localized: "store.product.aiMonthly")
    public static let storeAIYearly = String(localized: "store.product.aiYearly")
    public static let storeCloudMonthly = String(localized: "store.product.cloudMonthly")
    public static let storeTipSmall = String(localized: "store.product.tipSmall")
    public static let storeTipMedium = String(localized: "store.product.tipMedium")
    public static let storeTipLarge = String(localized: "store.product.tipLarge")
    public static let storeRestorePurchases = String(localized: "store.restorePurchases")
    public static let storeTipHeader = String(localized: "store.tipHeader")

    // MARK: - Features (功能描述)
    public static let featureBasicReader = String(localized: "feature.basicReader")
    public static let featureBasicReaderDesc = String(localized: "feature.basicReaderDesc")
    public static let featureLocalImport = String(localized: "feature.localImport")
    public static let featureLocalImportDesc = String(localized: "feature.localImportDesc")
    public static let featureMangaSingle = String(localized: "feature.mangaSingle")
    public static let featureMangaSingleDesc = String(localized: "feature.mangaSingleDesc")
    public static let featureBasicPanels = String(localized: "feature.basicPanels")
    public static let featureBasicPanelsDesc = String(localized: "feature.basicPanelsDesc")
    public static let featureAllModes = String(localized: "feature.allModes")
    public static let featureAllModesDesc = String(localized: "feature.allModesDesc")
    public static let featureOPSDSupport = String(localized: "feature.opdsSupport")
    public static let featureOPSDSupportDesc = String(localized: "feature.opdsSupportDesc")
    public static let featureAdvancedMeta = String(localized: "feature.advancedMeta")
    public static let featureAdvancedMetaDesc = String(localized: "feature.advancedMetaDesc")
    public static let featureBackup = String(localized: "feature.backup")
    public static let featureBackupDesc = String(localized: "feature.backupDesc")
    public static let featureSmartLists = String(localized: "feature.smartLists")
    public static let featureSmartListsDesc = String(localized: "feature.smartListsDesc")
    public static let featureGestureCustom = String(localized: "feature.gestureCustom")
    public static let featureGestureCustomDesc = String(localized: "feature.gestureCustomDesc")
    public static let featureAIPanels = String(localized: "feature.aiPanels")
    public static let featureAIPanelsDesc = String(localized: "feature.aiPanelsDesc")
    public static let featureAdvancedTTS = String(localized: "feature.advancedTTS")
    public static let featureAdvancedTTSDesc = String(localized: "feature.advancedTTSDesc")
    public static let featurePencil = String(localized: "feature.pencil")
    public static let featurePencilDesc = String(localized: "feature.pencilDesc")
    public static let featureThemesAll = String(localized: "feature.themesAll")
    public static let featureThemesAllDesc = String(localized: "feature.themesAllDesc")
    public static let featureVocab = String(localized: "feature.vocab")
    public static let featureVocabDesc = String(localized: "feature.vocabDesc")
    public static let featureAIUpscale = String(localized: "feature.aiUpscale")
    public static let featureAIUpscaleDesc = String(localized: "feature.aiUpscaleDesc")
    public static let featureOCRTranslate = String(localized: "feature.ocrTranslate")
    public static let featureOCRTranslateDesc = String(localized: "feature.ocrTranslateDesc")
    public static let featureAISummary = String(localized: "feature.aiSummary")
    public static let featureAISummaryDesc = String(localized: "feature.aiSummaryDesc")
    public static let featureICloudSync = String(localized: "feature.iCloudSync")
    public static let featureICloudSyncDesc = String(localized: "feature.iCloudSyncDesc")
    public static let featureWebDAVSync = String(localized: "feature.webdavSync")
    public static let featureWebDAVSyncDesc = String(localized: "feature.webdavSyncDesc")
    public static let featureCrossDevice = String(localized: "feature.crossDevice")
    public static let featureCrossDeviceDesc = String(localized: "feature.crossDeviceDesc")

    // MARK: - Gesture Presets
    public static let gesturePresetManga = String(localized: "gesture.preset.manga")
    public static let gesturePresetWestern = String(localized: "gesture.preset.western")
    public static let gesturePresetWebtoon = String(localized: "gesture.preset.webtoon")
    public static let gesturePresetNovel = String(localized: "gesture.preset.novel")
    public static let gesturePresetKindle = String(localized: "gesture.preset.kindle")
    public static let gesturePresetMinimal = String(localized: "gesture.preset.minimal")

    // MARK: - Smart List
    public static let smartListContinueReading = String(localized: "smartlist.continueReading")
    public static let smartListRecentlyAdded = String(localized: "smartlist.recentlyAdded")
    public static let smartListUnread = String(localized: "smartlist.unread")
    public static let smartListCompleted = String(localized: "smartlist.completed")

    // MARK: - Accessibility
    public static let accessibilityColorBlindNone = String(localized: "accessibility.colorBlind.none")
    public static let accessibilityColorBlindProtanopia = String(localized: "accessibility.colorBlind.protanopia")
    public static let accessibilityColorBlindDeuteranopia = String(localized: "accessibility.colorBlind.deuteranopia")
    public static let accessibilityColorBlindTritanopia = String(localized: "accessibility.colorBlind.tritanopia")
    public static let accessibilityColorBlindGrayscale = String(localized: "accessibility.colorBlind.grayscale")
    public static let accessibilityNextPage = String(localized: "accessibility.nextPage")
    public static let accessibilityPreviousPage = String(localized: "accessibility.previousPage")
    public static let accessibilityPanelsDetected = String(localized: "accessibility.panelsDetected")
    public static let accessibilityComicPage = String(localized: "accessibility.comicPage")

    // MARK: - Goals
    public static let goalDailyMinutes = String(localized: "goal.dailyMinutes")
    public static let goalDailyPages = String(localized: "goal.dailyPages")
    public static let goalWeeklyBooks = String(localized: "goal.weeklyBooks")
    public static let goalMonthlyBooks = String(localized: "goal.monthlyBooks")
    public static let goalCustom = String(localized: "goal.custom")
    public static let goalMinutes = String(localized: "goal.minutes")
    public static let goalPages = String(localized: "goal.pages")
    public static let goalBooks = String(localized: "goal.books")

    // MARK: - Icons (App Icon names)
    public static let iconDefault = String(localized: "icon.default")
    public static let iconDark = String(localized: "icon.dark")
    public static let iconOrange = String(localized: "icon.orange")
    public static let iconBlue = String(localized: "icon.blue")
    public static let iconGreen = String(localized: "icon.green")
    public static let iconPurple = String(localized: "icon.purple")
    public static let iconGold = String(localized: "icon.gold")
    public static let iconMono = String(localized: "icon.mono")
}
